#if !canImport(ObjectiveC)
import XCTest

extension NumbersAPIServiceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NumbersAPIServiceTests = [
        ("testFetchRandomYearFact", testFetchRandomYearFact),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(NumbersAPIServiceTests.__allTests__NumbersAPIServiceTests),
    ]
}
#endif
